server.port=8080

# pusher additions
pusher.appId=2140992
pusher.key=d10223ce93fd20bcd040
pusher.secret=55589a310d715c7d1184
pusher.cluster=eu

# Activate the 'dev' profile locally
spring.profiles.active=dev